### ISSUE TITLE
Add React prop to supplement list of fonts

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#13]
should accept list of objects with label and font name:

```
[{
  label: "Frank Ruhl",
  fontName: "Frank Ruhl Libre"
},
{...}
]
```

@jpuri suggested that "label" is optional (if not provided, `fontName` will be used for the label)

**Comment by jpuri** [comment]
I have added a new prop to the editor `customFonts`. The detail of the property are same as described above.
