### ISSUE TITLE
Save button - return canvas

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#16]
Crops canvas to content

Generates a new canvas element, cropped to content.

For examples:

- if there's only "Hello World" english text, it will be a small rectangle.
- if there's both English and Hebrew, it will be the full-width
- only in the case of using the entire screen area, will it be the full area

It should then call a callback which was supplied via a top-level prop, with both the original [targetCanvas](https://github.com/jewish-interactive/draft-canvas/issues/20)  and this newly created cropped canvas

The return here is in _addition_ to https://github.com/jewish-interactive/draft-canvas/issues/22

**Comment by jpuri** [comment]
Should this canvas element be hidden or visible to the user ?

**Comment by dakom** [comment]
It should be invisible - purely an in-memory node

**Comment by jpuri** [comment]
This feature is half implemented, save button is added and it sends back the rendered Canvas node, I am still working on the invisible canvas node.

**Comment by jpuri** [comment]
On save it will now return an object with 2 parameters `{rawDraftContentState, canvas}`.
