### ISSUE TITLE
Remove "Close" button feature

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#18]
The responsibility of rendering <DraftCanvas /> vs. `null` should be on the containing app

**Comment by dakom** [comment]
I've changed the title here - instead of a callback, the "close" functionality should be controlled by the higher-order component (any cleanup `DraftCanvas` needs to do should be handled in lifecycle).

Similarly, the design and placement of the close button is the responsibility of the calling app, not `DraftCanvas`

**Comment by jpuri** [comment]
Ah, ok let me remove the close functionality.
