### ISSUE TITLE
Re-mounting fails

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#19]
When embeded in a higher component and togged between mounted/un-mounted (e.g. rendering `null`, then `<DraftCanvas />`, then `null`, then `<DraftCanvas />` again - it is no longer visible on the second mounting

**Comment by jpuri** [comment]
Hey @dakom : can you plz share the higher component code. That will help me identify the issue.

**Comment by dakom** [comment]
Sure - I'll do that a bit later today :)

Note that it's somewhat related to issues #18 and #20 since it's "issues of embedding elsewhere"

These - #18, #19, #20 should be the top-priority for the next milestone. Would you like me to indicate that somewhere besides this comment?

**Comment by dakom** [comment]
Hmm... when I re-create the same scenario here it works fine (temporarily pushed in the [temp-remove branch](https://github.com/jewish-interactive/draft-canvas/tree/temp-remove))

I'll have to check into this deeper, will assign this issue to myself for now. Feel free to ignore it... #20 is the current highest priority. Thanks!

**Comment by jpuri** [comment]
This might be related to `ref` being called only once, though I am not sure.

**Comment by dakom** [comment]
Seems to be fixed now :)
