### ISSUE TITLE
Missing text when Hebrew + Styling

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#2]
Adding some Hebrew text and then styling some of it causes words to go missing:

![screen shot 2018-01-29 at 10 53 28](https://user-images.githubusercontent.com/6406986/35501483-c2e9fe88-04e2-11e8-8d38-9c514c8dccc5.png)

**Comment by dakom** [comment]
Is this ticket closed? If so - feel free to close it :)

For future reference - closing it should automatically move it to the "done" priority

**Comment by jpuri** [comment]
Yep this is closed. Sound good 👍
