### ISSUE TITLE
Highlighting a word in a Hebrew sentence is problematic

### ISSUE THREAD

**Issue by corinnewo** [jewish-interactive/draft-canvas#24]
I inserted a sentence from Sefaria, and selected a word to highlight. In the left hand block, the highlight is good, but in the preview blo
![highlighting in hebrew is problematic](https://user-images.githubusercontent.com/16290361/36095004-0a56569c-0ff9-11e8-9f67-df07c0b4e1f2.PNG)
ck, the wrong part is highlighted.

**Comment by jpuri** [comment]
The issue has been fixed.
