### ISSUE TITLE
The Sefaria button is transparent. Please make it on same background as the other buttons

### ISSUE THREAD

**Issue by corinnewo** [jewish-interactive/draft-canvas#31]
![transparent sefaria button](https://user-images.githubusercontent.com/16290361/36469423-dd604d0c-16ef-11e8-87f8-d6435de297ef.PNG)
![sefarya_button_normal 2x](https://user-images.githubusercontent.com/16290361/36469434-e319244e-16ef-11e8-92ba-6fb2ba74e57a.png)

Please can you either put in a background to the button, or use the attached Sefaria graphic for the button?
Thanks!

**Comment by jpuri** [comment]
White background has been added to whole editor.
