### ISSUE TITLE
Cropping not taking into account Hebrew

### ISSUE THREAD

**Issue by corinnewo** [jewish-interactive/draft-canvas#32]
I am not sure if this is for you Jyoti or for David!
But when you have Hebrew and English in the editor, then when you insert into the Ji Tap screen, the Hebrew is cropped off. I am attaching the text as seen in the editor, and then inserted into Ji Tap.
![cropping not taking into account hebrew - cropped](https://user-images.githubusercontent.com/16290361/36470050-27c1bf82-16f2-11e8-8274-fcb64f46e6a3.PNG)
![text editor with all hebrew before cropping](https://user-images.githubusercontent.com/16290361/36470051-27ef394e-16f2-11e8-8107-dfc16291e6c4.PNG)

**Comment by jpuri** [comment]
@corinnewo : this issue is in editor code, I need to fix this.

Thanks for reporting this bug :)

**Comment by jpuri** [comment]
Issue has been fixed.
