### ISSUE TITLE
Bug in save

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/draft-canvas#34]
Try saving with the following text:
 (may need to copy/paste from plain text editor to remove formatting)

```
שלום
הם קוראים לי דוד
מה שלומך?
```

In the example, this produces the following, the text gets squished

![image](https://user-images.githubusercontent.com/6406986/36714106-7281a8d8-1b99-11e8-950e-02fca5d903c1.png)

**Comment by jpuri** [comment]
This might be some css effect in main application.

**Comment by dakom** [comment]
I added the "save" demo functionality (see issue #33 ) - the above happens in this repo's example

**Comment by dakom** [comment]
Note for @jpuri from our Zoom call, seems to be when it's only Hebrew

**Comment by jpuri** [comment]
The issue has been fixed.
